Fix `docker compose` deploy (#6)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,7 +18,6 @@ env:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
@@ -39,9 +38,11 @@ jobs:
         if [[ "${{ github.event_name }}" == "push" ]]; then
           echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
           echo "IMAGE_TAG=prod-${{ github.sha }}" >> $GITHUB_ENV
+          echo "PORT_MAPPING=80:80" >> $GITHUB_ENV
         else
           echo "DEPLOY_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
           echo "IMAGE_TAG=${{ github.event.inputs.environment }}-${{ github.sha }}" >> $GITHUB_ENV
+          echo "PORT_MAPPING=8080:80" >> $GITHUB_ENV
         fi
 
     - name: Build, tag, and push image to Amazon ECR
@@ -49,7 +50,7 @@ jobs:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
       run: |
         docker compose build app
-        docker tag referendumapi_app:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}
+        docker tag referendumapi-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}
 
     - name: Deploy to EC2
@@ -62,15 +63,32 @@ jobs:
           --parameters '{
             "commands": [
               "aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
-              "echo \"ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}\" > .env",
-              "echo \"ECR_REPOSITORY=${{ env.ECR_REPOSITORY }}\" >> .env",
-              "echo \"IMAGE_TAG=${{ env.IMAGE_TAG }}\" >> .env",
-              "docker compose -f docker-compose.prod.yml down",
-              "docker compose -f docker-compose.prod.yml up -d",
-              "echo ${{ env.DEPLOY_ENV }} deployment completed successfully!"
+              "docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}",
+              "docker stop ${{ env.DEPLOY_ENV }}-app || true",
+              "docker rm ${{ env.DEPLOY_ENV }}-app || true",
+              "docker run -d --name ${{ env.DEPLOY_ENV }}-app -p ${{ env.PORT_MAPPING }} ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}",
+              "echo ${{ env.DEPLOY_ENV }} deployment completed"
             ]
           }'
 
     - name: Verify Deployment
       run: |
-        aws ec2 describe-instance-status --instance-ids ${{ env.EC2_INSTANCE_ID }}
+        sleep 30
+        HEALTH_CHECK_COMMAND_ID=$(aws ssm send-command \
+          --instance-ids "${{ env.EC2_INSTANCE_ID }}" \
+          --document-name "AWS-RunShellScript" \
+          --parameters '{"commands":["curl -s -o /dev/null -w \"%{http_code}\" http://localhost:8080/health"]}' \
+          --output text \
+          --query "Command.CommandId")
+        HEALTH_CHECK_STATUS_CODE=$(aws ssm list-command-invocations \
+          --command-id "$HEALTH_CHECK_COMMAND_ID" \
+          --details \
+          --output text \
+          --query "CommandInvocations[].CommandPlugins[].Output")
+        
+        if [ "$HEALTH_CHECK_STATUS_CODE" != "200" ]; then
+          echo "Deployment verification failed. Health check returned: $HEALTH_CHECK"
+          exit 1
+        fi
+        
+        echo "Deployment verified"
